import type { Metadata } from "next";
import "./globals.css";

/**
 * Metadata for the page
 */
export const metadata: Metadata = {
  title: "SpaceCoin Orbitalk",
  description: "Generated by @vikiival with love",
};

/**
 * Root layout for the page
 *
 * @param {object} props - The props for the root layout
 * @param {React.ReactNode} props.children - The children for the root layout
 * @returns {React.ReactNode} The root layout
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 dark:bg-gray-900 dark flex flex-col min-h-screen">
        {/* Header (Fixed Height) */}
        <header className="py-6 flex items-center justify-between relative">
          <img
            src="https://raw.githubusercontent.com/spacecoinxyz/media-kit/c240a7a470fdb31219459ebb98a8a72e927a49a5/spacecoin_v1/spacecoin_logotype/spacecoin_logo_dark.svg"
            alt="Coinbase"
            className="h-8 ml-4"
          />

          <span className="absolute left-1/2 transform -translate-x-1/2 text-3xl font-bold text-yellow-600 dark:text-yellow-400">
            Orbitalk (OMI)
          </span>
        </header>

        {/* Main Content (Dynamic, Grows but Doesn't Force Scroll) */}
        <main className="flex-grow flex items-center justify-center px-4">{children}</main>

        {/* Footer (Fixed Height) */}
        <footer className="py-4 text-center text-gray-500 dark:text-gray-400 flex-none">
          <img
            src="https://raw.githubusercontent.com/spacecoinxyz/media-kit/c240a7a470fdb31219459ebb98a8a72e927a49a5/spacecoin_v1/spacecoin_logotype/spacecoin_logo_dark.svg"
            alt="Coinbase"
            className="h-6 mx-auto mb-2"
          />
          <div className="mt-2">
            <a
              href="https://github.com/spacecoinxyz"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:underline text-yellow-600 dark:text-yellow-400"
            >
              GitHub
            </a>{" "}
            |{" "}
            <a
              href="https://github.com/spacecoinxyz/research/blob/main/publications/Blue-Paper-Spacecoinxyz.pdf"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:underline text-yellow-600 dark:text-yellow-400"
            >
              Documentation
            </a>{" "}
          </div>
          <p className="text-xs text-gray-400 mt-2">© {new Date().getFullYear()} Space Friends</p>
        </footer>
      </body>
    </html>
  );
}
